### ISSUE TITLE
[Discussion] Regarding the palette

### ISSUE THREAD

**Issue by AleksandarV993** [KoBeWi/Godot-Palette-Swap-Shader#5]
Not really an issue, mostly a discussion since I couldn't find a way to contact you via e-mail. 

I've looked around for a while and couldn't find any answers to the following issue. 
Let's say that the palette shader should be permanent on any type of a Sprite. 
For example, you've got a playable character and the player has changed some colors on the Sprite, you would want those colors to be permanent no matter the situation. 
But what happens when you would like to apply any other modifications to that Sprite? For example, any type of flash effect or anything, it would remove the previous material / shader, and set the new one. 
Is there a way to blend these together? Is there a way to have multiple passes on a CanvasItem shader and have them co-exist with each other? 

I'm pretty new to shaders myself so I have no idea what would be the best way to go though this. 
I could have a single 'super-shader' where I would have multiple functions and flags, and based on that certain parts of the shader would activate. 
I also assume that I could have multiple textures / sprites / materials, and bind them together and call them on the go (but this would probably get out of hand really fast).

So in general, I wanted to ask someone who is far more experienced than I am, what would be the common practice here and how would you tackle that problem?

**Comment by KoBeWi** [comment]
Well, there are a few solutions to this problem:
- the multiple passes you mentioned are unfortunately not available. Material has `next_pass` property, but it's not implemented in 2D (AFAIK)
- you can use the "super shader" by utilizing shader includes. This would at least allow you to avoid huge shaders
- another option is baking the texture. You can put your recolored sprite into a SubViewport and fetch its texture. The only problem is that it always takes a couple of frames, because the texture needs a time to render
- you could also try making other effects non-shader. E.g. flash effect can be easily done with a Tween

Pick whatever suits you best. If you are able, the viewport approach might be the best one, because you won't need the shader active at all time, saving some CPU power (though it's only relevant for big sprites). However if you can't delay changing colors, shader includes are probably your best option (assuming you really need multiple shaders).
